// What SurView measures on images it did not make, against an answer it did not
// write.
//
// WHY THIS EXISTS. Every other accuracy case in this suite measures our own
// synthetic examples against the answer our own generator states. That is sound
// verification of the IMPLEMENTATION -- it says the code computes what we
// intended -- and it says nothing whatever about whether what we intended
// agrees with the field. Until 2026-09-14 nothing in this project had ever
// checked SurView against anything but itself, and the ROADMAP called that the
// largest single gap in its evidence.
//
// The images here are the iDICs/SEM DIC Challenge 1.0 Sample 3 set: a speckle
// reference and eleven targets rigidly shifted by 0.00 to 1.00 px in steps of
// 0.10, generated by somebody else, by a method that is not ours, with the
// prescribed shift stated in each file's own NAME.
//
// ⚑ THE ANSWER HERE IS PRESCRIBED, NOT EXACT BY CONSTRUCTION, and the
// difference matters. Our synthetic sets render each frame afresh from an
// analytic pattern, so no pixel is ever resampled and the stated answer IS the
// truth. This set was made by shifting one photograph in the Fourier domain and
// adding about two grey levels of noise, so the image carries whatever that
// resampling and that noise do. A disagreement here is therefore evidence about
// the pair of us, not proof about us alone -- which is exactly what makes it
// worth having, and exactly why the tolerance below is not the tolerance the
// synthetic cases use.
//
// ⚑ THE DATA IS NOT IN THIS REPOSITORY AND MUST NOT BE. The challenge sets
// state no licence or terms of use; they may be used, and whether they may be
// redistributed is unestablished (see the MANIFEST beside the download). So
// these cases read the set from wherever it was unpacked, named by
// SURVIEW_DIC_CHALLENGE_SAMPLE3, and SKIP when it is not there. A fresh clone
// and CI run the parser cases below and skip the measurement, which is the
// honest arrangement rather than a silently absent check: the run says
// "skipped", not "passed".
//
// NEGATIVE CHECK (2026-09-14), each reverted after:
//   - the stated shift read as x for both components: the lopsided-name case
//     went red, the measurement case did NOT (see the limitation below).
//   - the sign of the parsed shift flipped: both parser cases and the
//     measurement went red.
//   - a name with no X token read as a shift of zero instead of refusing:
//     `a_name_that_states_no_shift_is_not_a_shift_of_zero` went red.
//   - the guard refusing an unstated answer removed: a field measuring no
//     movement then agreed perfectly with an answer nobody gave, and
//     `a_measurement_set_against_no_stated_answer_agrees_with_nothing` went red.
//   - the tolerance widened to 0.1 px: the measurement stayed green, which is
//     why the tolerance is argued from the bias below rather than chosen to
//     fit.
//   - the name read with QFileInfo::baseName instead of completeBaseName: four
//     of the reading cases went red, because baseName stops at the first dot
//     and that dot is inside the shift itself.
//
// ⚑ WHAT THIS DOES NOT CATCH, stated because it looks like coverage and is
// not: every frame in Sample 3 shifts EQUALLY in x and y, so the measurement
// case cannot tell u from v, and a build that reported u for both components
// would pass it. That is the fixture-agrees-with-itself trap this project has
// earned four times over. The parser half is closed by a lopsided name below;
// the measurement half wants Sample 14, whose displacement is in x alone, and
// SurView cannot open Sample 14 today (its reference and targets differ by one
// pixel in width and the run refuses them). Recorded in the ROADMAP.

#include "core/Correlation.h"
#include "core/DicChallenge.h"
#include "core/Roi.h"

#include <QDir>
#include <QTest>

#include <cmath>

namespace
{

// Coarse on purpose, and first order on purpose. A rigid shift is exactly what
// a first-order shape function describes, so this case measures whether the
// answer is right rather than how hard the solver can be made to work.
CorrelationSettings settings()
{
    CorrelationSettings s;
    s.solver = CorrelationSettings::ICGN;
    s.shapeOrder = 1;
    s.subsetRadius = 16;
    s.gridStep = 16;
    s.maxIterations = 15;
    s.convergence = 0.001;
    s.strainEnabled = false;
    return s;
}

CorrelationResult measure(const QString &reference, const QString &target)
{
    CorrelationRunner runner(settings(), RegionOfInterest(), reference, target);
    CorrelationResult result;
    QString failure;
    QObject::connect(&runner, &CorrelationRunner::finished,
                     [&result](const CorrelationResult &r) { result = r; });
    QObject::connect(&runner, &CorrelationRunner::failed,
                     [&failure](const QString &reason) { failure = reason; });
    runner.run();
    if (!failure.isEmpty())
        qWarning("correlation failed: %s", qPrintable(failure));
    return result;
}

QString sampleDirectory()
{
    return qEnvironmentVariable("SURVIEW_DIC_CHALLENGE_SAMPLE3");
}

}  // namespace

class TestCrossValidation : public QObject
{
    Q_OBJECT

private slots:
    void a_challenge_file_name_states_the_shift_it_carries();
    void a_shift_that_differs_in_x_and_y_is_read_in_the_right_order();
    void a_name_that_states_no_shift_is_not_a_shift_of_zero();
    void a_name_stating_only_one_axis_states_no_shift();
    void a_stated_shift_of_zero_is_a_statement_not_an_absence();
    void the_other_numbers_in_a_challenge_name_are_not_the_shift();

    void the_agreement_reports_each_axis_against_its_own_stated_value();
    void an_unconverged_point_is_left_out_of_the_agreement();
    void an_agreement_over_no_points_is_refused_not_reported_as_exact();
    void a_measurement_set_against_no_stated_answer_agrees_with_nothing();

    void an_external_rigid_shift_is_measured_as_the_shift_it_states();
};

// --- reading the answer ---------------------------------------------------

void TestCrossValidation::a_challenge_file_name_states_the_shift_it_carries()
{
    const DicChallengeShift shift =
        dicChallengeShiftFromFileName(QStringLiteral("Sample3-003 X0.30 Y0.30 N2 C0 R0.tif"));
    QVERIFY(shift.stated);
    QCOMPARE(shift.x, 0.30);
    QCOMPARE(shift.y, 0.30);
}

// ⚑ Every frame the challenge ships states the same number for both axes, so a
// reader that returned x for both would satisfy every real name in the set.
// This name is lopsided in the one axis the code could confuse.
void TestCrossValidation::a_shift_that_differs_in_x_and_y_is_read_in_the_right_order()
{
    const DicChallengeShift shift =
        dicChallengeShiftFromFileName(QStringLiteral("Sample3-003 X0.30 Y-0.70 N2 C0 R0.tif"));
    QVERIFY(shift.stated);
    QCOMPARE(shift.x, 0.30);
    QCOMPARE(shift.y, -0.70);
}

// The standing rule of this code base, one file format further out: an absence
// is not a zero. The reference frame states no shift at all, and reading it as
// 0.00 would set a measurement against an answer nobody gave.
void TestCrossValidation::a_name_that_states_no_shift_is_not_a_shift_of_zero()
{
    const DicChallengeShift shift =
        dicChallengeShiftFromFileName(QStringLiteral("Sample3 Reference.tif"));
    QVERIFY(!shift.stated);
}

void TestCrossValidation::a_name_stating_only_one_axis_states_no_shift()
{
    QVERIFY(!dicChallengeShiftFromFileName(QStringLiteral("Sample3-003 X0.30 N2 C0 R0.tif")).stated);
    QVERIFY(!dicChallengeShiftFromFileName(QStringLiteral("Sample3-003 Y0.30 N2 C0 R0.tif")).stated);
}

// The other half of the rule above: a frame that really does state a shift of
// zero is an answer, and must be usable as one.
void TestCrossValidation::a_stated_shift_of_zero_is_a_statement_not_an_absence()
{
    const DicChallengeShift shift =
        dicChallengeShiftFromFileName(QStringLiteral("Sample3-000 X0.00 Y0.00 N2 C0 R0.tif"));
    QVERIFY(shift.stated);
    QCOMPARE(shift.x, 0.0);
    QCOMPARE(shift.y, 0.0);
}

// Sample 5 varies contrast and noise per frame, so a name carries C and R and N
// numbers beside the shift. Reading the wrong token would report a shift of 100
// px and be perfectly obvious; reading R25 as a y shift of 25 would not be.
void TestCrossValidation::the_other_numbers_in_a_challenge_name_are_not_the_shift()
{
    const DicChallengeShift shift =
        dicChallengeShiftFromFileName(QStringLiteral("Sample5-009 X0.90 Y0.90 N2 C100 R10.tif"));
    QVERIFY(shift.stated);
    QCOMPARE(shift.x, 0.90);
    QCOMPARE(shift.y, 0.90);
}

// --- setting a measurement against it -------------------------------------

void TestCrossValidation::the_agreement_reports_each_axis_against_its_own_stated_value()
{
    QVector<CorrelationPoint> points;
    for (int i = 0; i < 4; ++i) {
        CorrelationPoint p;
        p.converged = true;
        p.u = 0.55f;   // stated 0.50, so 0.05 out
        p.v = 0.17f;   // stated 0.20, so 0.03 under -- lopsided in both size
        points.append(p); //                            and sign
    }

    DicChallengeShift stated;
    stated.stated = true;
    stated.x = 0.50;
    stated.y = 0.20;

    const ShiftAgreement agreement = agreementWithStatedShift(points, stated);
    QVERIFY(agreement.measured);
    QCOMPARE(agreement.solved, 4);
    QVERIFY(std::abs(agreement.errorX - 0.05) < 1e-6);
    QVERIFY(std::abs(agreement.errorY + 0.03) < 1e-6);
    // The worst of the two, as a magnitude, so one number can be asserted on.
    QVERIFY(std::abs(agreement.worstError - 0.05) < 1e-6);
}

// A rejected point holds the solver's leftover guess, not a displacement. The
// standing rule everywhere else in this code base, applied here.
void TestCrossValidation::an_unconverged_point_is_left_out_of_the_agreement()
{
    QVector<CorrelationPoint> points;
    CorrelationPoint good;
    good.converged = true;
    good.u = 0.50f;
    good.v = 0.20f;
    points.append(good);

    CorrelationPoint rejected;
    rejected.converged = false;
    rejected.u = 900.f;
    rejected.v = -900.f;
    points.append(rejected);

    DicChallengeShift stated;
    stated.stated = true;
    stated.x = 0.50;
    stated.y = 0.20;

    const ShiftAgreement agreement = agreementWithStatedShift(points, stated);
    QCOMPARE(agreement.solved, 1);
    QVERIFY(agreement.worstError < 1e-6);
}

// ⚑ A field that measured nothing agrees with nothing. Reported as an error of
// zero it would be the most flattering reading available, and a run that lost
// every point would pass the case below outright.
void TestCrossValidation::an_agreement_over_no_points_is_refused_not_reported_as_exact()
{
    QVector<CorrelationPoint> none;
    DicChallengeShift stated;
    stated.stated = true;
    stated.x = 0.50;
    stated.y = 0.50;

    const ShiftAgreement agreement = agreementWithStatedShift(none, stated);
    QVERIFY(!agreement.measured);
    QCOMPARE(agreement.solved, 0);
}

// ⚑ The reference frame states no shift, and a default-constructed stated shift
// holds 0.0 in both axes. Set against one, a field that really did measure no
// movement would report perfect agreement with an answer nobody gave.
void TestCrossValidation::a_measurement_set_against_no_stated_answer_agrees_with_nothing()
{
    QVector<CorrelationPoint> points;
    CorrelationPoint p;
    p.converged = true;
    p.u = 0.f;
    p.v = 0.f;
    points.append(p);

    const DicChallengeShift unstated =
        dicChallengeShiftFromFileName(QStringLiteral("Sample3 Reference.tif"));
    QVERIFY(!unstated.stated);

    const ShiftAgreement agreement = agreementWithStatedShift(points, unstated);
    QVERIFY(!agreement.measured);
}

// --- the measurement itself ------------------------------------------------

void TestCrossValidation::an_external_rigid_shift_is_measured_as_the_shift_it_states()
{
    const QString dir = sampleDirectory();
    if (dir.isEmpty()) {
        QSKIP("SURVIEW_DIC_CHALLENGE_SAMPLE3 is not set, so the external set is "
              "not available here. tools/cross-validate.sh unpacks it and sets it.");
    }

    const QString reference = dir + QStringLiteral("/Sample3 Reference.tif");
    QVERIFY2(QFile::exists(reference),
             qPrintable(QStringLiteral("no reference image at ") + reference));

    const QStringList targets =
        QDir(dir).entryList({QStringLiteral("Sample3-0*.tif")}, QDir::Files, QDir::Name);
    // If this is wrong, every assertion below is vacuous: a loop over nothing
    // passes.
    QCOMPARE(targets.size(), 11);

    for (const QString &name : targets) {
        const DicChallengeShift stated = dicChallengeShiftFromFileName(name);
        QVERIFY2(stated.stated, qPrintable(QStringLiteral("no stated shift in ") + name));

        const CorrelationResult result = measure(reference, dir + "/" + name);
        const ShiftAgreement agreement =
            agreementWithStatedShift(result.points, stated);

        QVERIFY2(agreement.measured, qPrintable(QStringLiteral("nothing solved on ") + name));
        // ⚑ 841 OF 900, AND THE MISSING 59 ARE STRUCTURAL RATHER THAN A
        // PROPERTY OF THIS SET. They are exactly the grid's first row and
        // first column -- the points whose subset touches pixel 0 -- and they
        // fail on every frame including the one shifted by nothing at all, so
        // they are not about the shift, the noise or the speckle. A subset
        // starting exactly at the image edge leaves the target interpolator no
        // pixel outside itself to work with. Recorded in the ROADMAP; the bar
        // here is set below it so this case measures ACCURACY and does not
        // silently become the place that grid defect is pinned.
        QVERIFY2(agreement.solved > 800,
                 qPrintable(QStringLiteral("only %1 of %2 points solved on %3")
                                .arg(agreement.solved)
                                .arg(result.points.size())
                                .arg(name)));

        // ⚑ A HUNDREDTH OF A PIXEL, AND THE NUMBER IS ARGUED RATHER THAN
        // FITTED. Measured across all eleven frames the worst disagreement is
        // 0.0032 px, and it is not scatter: it traces the S-shaped sub-pixel
        // interpolation bias every subset-based method carries -- zero at 0.0,
        // 0.5 and 1.0 px, negative below half a pixel and positive above, with
        // a period of exactly one pixel. That bias is a property of the method
        // and of their resampling together, so the tolerance has to leave room
        // for it rather than pretend it away. A hundredth of a pixel is the
        // figure the synthetic translation case already claims, it is three
        // times the bias actually seen, and it is tight enough that any of the
        // sign, axis and scale mistakes this path can make would breach it by
        // an order of magnitude.
        QVERIFY2(agreement.worstError < 0.01,
                 qPrintable(QStringLiteral("%1: measured (%2, %3) against stated "
                                           "(%4, %5), worst error %6 px")
                                .arg(name)
                                .arg(agreement.meanU, 0, 'f', 5)
                                .arg(agreement.meanV, 0, 'f', 5)
                                .arg(stated.x, 0, 'f', 2)
                                .arg(stated.y, 0, 'f', 2)
                                .arg(agreement.worstError, 0, 'f', 5)));
    }
}

QTEST_MAIN(TestCrossValidation)
#include "test_cross_validation.moc"
